version: "3.9"

services:
  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dockerdemo
    container_name: mysqlcontainer
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  mypythonapp:
    build: .
    container_name: mypython
    depends_on:
      mysqldb:
        condition: service_healthy
    stdin_open: true
    tty: true
